AWSTemplateFormatVersion: '2010-09-09'
Description: ''
Resources:
  MyFunction:
    Properties:
      CodeUri: s3://elephpants-in-the-sky/stacks/604d0991694b44cbaafed241be3bf0e9
      Description: ''
      FunctionName: elephpants-in-the-sky
      Handler: index.php
      Layers:
      - arn:aws:lambda:us-east-1:209497400698:layer:php-73:4
      MemorySize: 1024
      Runtime: provided
      Timeout: 10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31

