language: generic
dist: xenial
before_install:
- phpenv global 7.2
install:
- pip install --user awscli
- pip install --user aws-sam-cli
- npm install -g serverless
script:
- composer install --optimize-autoloader
- composer test
deploy:
  provider: script
  script: composer deploy
  skip_cleanup: true
  on:
    repo: guillermoandrae/elephpants-in-the-sky
env:
  global:
  - AWS_DEFAULT_REGION=us-east-1
  - secure: FrW6g0bZZaT49zqE2aqmDRD3R2dXRHe7nvgwhvKa6NSM/Hnzk6eTfDlnQTspVkxMYNk8PPOYTH11Ukl83KZStob/c5bwrlLEpBylvAftS++fbMzIdfitRh4ZQHz05ohzHtrxyXxNsrEj3Q9tUvBpzPnsla8GBu5OJk5am39QAxbwDRKE6daF/9PEqupw97ZN7cK3zWXLkWGIwhj45p1pzs/QZNi+pGousduYQ6LD4UnT7w4wz7cGYLKJKUAkjmu4s0Dzwq648C411Vtvx+2goAHEjX+xh0mL6UhK6ephTtM4xanxNXxOBtZrp/GoyYJS1fsAwGaURA3JpY0SSQUCE/04iY3KXWkqk82swUvZ76uo4v/g8Gr4ZZC18eztYVL/ZTBtKXap2aUvYeB3wR4BFECSQswOqhSO9GMLTXZmRbEyt9eWpc67e9Q1kWr3jL7pOWggybUgrNZrDq9gsYBCpwscFcZ0g+NztSXoO4MiW1U7F+odg7VHVzKQMnFkPA3vojfhGUdP9FkdFfbShyI231XrYW0RSD2SgE9d2eIDF7+lOu/foTbNn/XOX4JaaAgu+5H7xesjDapLD6ofPaJPztUAe2Egwn15srUUzuxkiPf/E72QMXjbOTWBpTg41LTJaeoCbAtz1OCLmP/qCQdrWsoMzC3brT8n3pO4JWsZxTg=
  - secure: 1KG08ZDSMkxSrWoVNv0Mrh/ABEJkxLt4IB+vCNArnUyM7lT1lejitO5DOsnLLxYcjQhG9iWCipJ+nBNNX2SFnvSth/DbO64xsvK5VDAlKjep9y4+LVNP7+HfNmcMHHFbm1zqL13Xh/Qh16knXXCyb74RaT53LNV4D9VVYC0kjlfRC8un4QgqiLyXEzi7tf97jy8zbRD4PacZv2kyQuLQXnWhrOyApF6iqsuxYOt/UsurMD/zcQpQlsaRUeNzZbVvt1JaLazr1lJEm4zVEY90RVz0yU33I6SgC6KlzGW0x8D3WhumivY6rO5Y7zoOy1oWh9OR7hbZK3T8gZo+65xGV0HvOlLZ2XmX28vyPrwr3eOeEJF0WjetNp7CtAcfzOMfZSt85qXmXeyFiiAAWdGolEPTimyY46+vRyK6aXtzAkSDmzAZURnDJ0cW34ISldtFOn7cjeOvwBBHz8n8aPqGXD6Nn0Y884WNSQz1U6TPNIwnJ5SCMVTfZgC1L86ySSnS1wolKj0dn30So5XF9z+H265B7M+daz+xXBiHL5mjnwNi/+uZGSIFCJCqyCGXG2Y+v+xG4i/seLXCFg1k27uW40th8cy750fwtrYnRy2Giki+8LlP5mJkzaauob6eAow5BpL/ED5yzKaHInEU4zG9dJj7gb1YAPElvtsSkoL1QxA=
